//
//  OnboardingRouter.swift
//  Movies
//
//  Created by Carlos Villamizar on 13/10/20.
//  Copyright © 2020 Carlos Villamizar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol OnboardingRoutingLogic {
}

protocol OnboardingDataPassing {
    var dataStore: OnboardingDataStore? { get }
}

class OnboardingRouter: NSObject, OnboardingRoutingLogic, OnboardingDataPassing {
    weak var viewController: OnboardingViewController?
    var dataStore: OnboardingDataStore?
  
}
