//
//  OnboardingInteractor.swift
//  Movies
//
//  Created by Carlos Villamizar on 13/10/20.
//  Copyright © 2020 Carlos Villamizar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnboardingBusinessLogic {
    func doSomething(request: Onboarding.Something.Request)
}

protocol OnboardingDataStore {
}

class OnboardingInteractor: OnboardingBusinessLogic, OnboardingDataStore {
    var presenter: OnboardingPresentationLogic?
    var worker: OnboardingWorker?
  
    // MARK: Do something
    func doSomething(request: Onboarding.Something.Request) {
        worker = OnboardingWorker()
        worker?.doSomeWork()
    
        let response = Onboarding.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
